---
- name: elksible
  vars:
     port_contents: "{{ lookup('file', 'port') }}"
     NAME_contents: "{{ lookup('file', 'NAME') }}"
  hosts: "{{ NAME_contents }}"
  become: True
  become_method: sudo
  tasks:
  - name: Elastic Search
    docker:
      name: "{{ NAME_contents }}-es"
      image: elasticsearch:latest
      state: reloaded
      restart_policy: always
      ports:
        - "9200:9200"
        - "9300:9300"
        - "9200:9200/udp"
        - "9300:9300/udp"
  - name: Logstash
    docker:
      name: "{{ NAME_contents }}-logstash"
      image: logstash
      state: reloaded
      restart_policy: always
      expose:
        - "9292"
        - "9997"
        - "9998"
        - "9999"
      ports:
        - "0.0.0.0:9292:9292"
        - "0.0.0.0:9997:9997"
        - "0.0.0.0:9997:9997/udp"
        - "0.0.0.0:9998:9998"
        - "0.0.0.0:9999:9999/udp"
      links:
        - "{{ NAME_contents }}-es:es"
      volumes:
        - "/exports/git/confstash:/conf-dir"
      command: 'logstash -f /conf-dir/logstash.conf'
  - name: Kibana
    docker:
      name: "{{ NAME_contents }}-kibana"
      image: kibana
      state: reloaded
      restart_policy: always
      links:
        - "{{ NAME_contents }}-es:elasticsearch"
      ports:
        - "{{ port_contents }}:5601"
